name: Testing

# Temporarily disabled
on: []

jobs:
  build:
    runs-on: ubuntu-20.04
    container: archlinux:base-devel
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Checkout shared CI repo
      uses: actions/checkout@v2
      with:
        repository: lxqt/ci
        path: shared-ci
    - name: Build
      run: bash ./.ci/build.sh
